### ISSUE TITLE
Could you add i18n support

### ISSUE THREAD

**Issue by JoshYuJump** [Echosong/ES#1]
https://github.com/Echosong/ES/blob/68547cf9347fb516e11109378ad027bcfff9e043/src/controller/web/BaseController.php#L29

**Comment by Echosong** [comment]
演示，这不属于 框架的一部分，实际要使用的话分页这展示肯定要自己写的大部分情况下如果json直接给，这部分前端完成 O(∩_∩)O~，恩恩，可以更 “英特莱松拉”

**Comment by JoshYuJump** [comment]
👌
